# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20170310_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
